### ISSUE TITLE
Broken on Actions

### ISSUE THREAD

**Issue by sit-fricke** [blendbyte/nova-items-field#10]
When using the field on Actions it will not render any controls, only the label. This is because the `resolve` method is not called when the field is used within an action.

For my use case I found a workaround:
```php
        return Items::make(
            __('apiKey.field.ip_constraints'),
            'ip_constraints'
        )
            ->withMeta([
                'max' => false,
                'listFirst' => false,
            ])
            ->rules([
                'ip_constraints.*' => ['ip'],
            ]);
```
This also applies to all other default values like `createButtonValue` for example.

**Comment by bashgeek** [comment]
Thanks for reporting! This should be fixed now and be in the next release.
