### ISSUE TITLE
Validation rule issue with required and named key

### ISSUE THREAD

**Issue by WillyReyno** [blendbyte/nova-items-field#11]
Versions 
- blendbyte/nova-items-field .1.0
- laravel/framework 10.15.0
- laravel/nova 4.26.5

Hello, I have an issue with the package and validation rules, taking the following Item fields:

```
Items::make('Titles', 'titles')
                ->hideWhenCreating()
                ->rules(['titles' => 'required|min:1', 'titles.*' => 'required'])
                ->draggable()
                ->hideFromIndex()
                ->showOnPreview()
                ->listFirst(),
```

However, the rules are not working properly and I'm getting the following error: 

![Capture d’écran 2023-08-02 à 20 10 57](https://github.com/blendbyte/nova-items-field/assets/5576482/a27d1966-5a42-4dff-8fcb-d0aff5197aeb)

Which shouldn't happen because I already have at least one item.

However, the following does work: 

```
->rules([null => 'required|min:1', 'titles.*' => 'required'])
```

Am i doing something wrong or missing something?

**Comment by bashgeek** [comment]
You're right, there was a discrepancy between the documentation and how the validation actually worked. With the next version it should work the way you described, too.
