### ISSUE TITLE
InputType number not working when submitting form

### ISSUE THREAD

**Issue by DanielMcAssey** [blendbyte/nova-items-field#14]
When using inputType(number), when submitting a form it seems its using .trim() without checking the type, it doesn't work

**Comment by Anticom** [comment]
Similar issue here. I can't even add new items when input type is number.

**Comment by bashgeek** [comment]
Thanks for reporting!

**Comment by Anticom** [comment]
Hey @bashgeek, thanks for fixing the issue!

However I noticed an extraneous `console.log` in c4027a9, that's probably left from implementing the fix.
Doesn't hurt but wanted to give you a heads-up on it.
