### ISSUE TITLE
use 

### ISSUE THREAD

**Issue by vrgenl** [blendbyte/nova-items-field#6]
Awesome you guys took over nova-items-fields

I have a small addition, the JS form field supports DependendFormField with currentField but you guys haven't added it to the Items.php field

```php
use Laravel\Nova\Fields\SupportsDependentFields;

class Items extends Field
{
    use SupportsDependentFields;
}
```

That way we can use ->dependsOn()

**Comment by bashgeek** [comment]
Thanks!
