### ISSUE TITLE
Draggable zone prevents from selecting text on mobile

### ISSUE THREAD

**Issue by WillyReyno** [blendbyte/nova-items-field#8]
Hello again,

On mobile version of Nova, it's not possible to select text to copy, or move cursor within the inputs if draggable is enabled. 

Do you think it would be possible to have an option that put the draggable zone only on the burger icon? That way it would still be possible to move the mobile cursor within each input.

Thank you!

**Comment by bashgeek** [comment]
Thanks for reporting! This should be fixed now and be in the next release.
